### ISSUE TITLE
Predict race for an image in 10k US Adult Faces Database

### ISSUE THREAD

**Issue by daniel-acuna** [usc-sail/mica-race-from-face#4]
Thanks for sharing the code to run a race prediction model. 

I've been trying to apply your pre-trained model on a sample of the 10k faces dataset without much success. In particular, most faces are predicted to be "black race".

One of the issues, I think, is that your code is missing (maybe?) how you preprocess an arbitrary face image before you input it into the network. 

Any help would be highly appreciated!

**Comment by zhouwei5113** [comment]
how to deal with the training sample with multi-label?

**Comment by JohnMBrandt** [comment]
Hey - I just used this pretained network on my own dataset, the only thing I had to do to preprocess the image was to make sure it was black and white and 100x100 px, which I did with the following chunk of code around the cv2.imread section.

`cv2.resize(self.img, (100,100), interpolation = cv2.INTER_CUBIC)`

**Comment by krsna6** [comment]
Could you please share the 10K dataset with me so I can test the models in more detail.

**Comment by krsna6** [comment]
If you can share how the models are performing on your datasets, that would be very helpful to me.
